name = "bptimer-panel"
compatibility_date = "2025-10-24"
workers_dev = false
preview_urls = false
send_metrics = false

[assets]
directory = ".svelte-kit/cloudflare/"
not_found_handling = "single-page-application"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 0.1
invocation_logs = true