#[rustfmt::skip]
// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActorBodyPartInfo {
    #[prost(int32, tag = "1")]
    pub part_id: i32,
    #[prost(uint64, tag = "2")]
    pub hp: u64,
    #[prost(uint64, tag = "3")]
    pub max_hp: u64,
    #[prost(enumeration = "BodyPartState", tag = "4")]
    pub state: i32,
    #[prost(int32, tag = "5")]
    pub fleshy_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActorBodyPartInfos {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(message, repeated, tag = "2")]
    pub infos: ::prost::alloc::vec::Vec<ActorBodyPartInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AoiSyncDelta {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(message, optional, tag = "2")]
    pub attrs: ::core::option::Option<AttrCollection>,
    #[prost(message, optional, tag = "3")]
    pub temp_attrs: ::core::option::Option<TempAttrCollection>,
    #[prost(message, optional, tag = "4")]
    pub event_data_list: ::core::option::Option<EventDataList>,
    #[prost(message, optional, tag = "5")]
    pub bullet_event: ::core::option::Option<BulletEvent>,
    #[prost(message, optional, tag = "6")]
    pub body_part_infos: ::core::option::Option<ActorBodyPartInfos>,
    #[prost(message, optional, tag = "7")]
    pub skill_effects: ::core::option::Option<SkillEffect>,
    #[prost(message, optional, tag = "8")]
    pub passive_skill_infos: ::core::option::Option<SeqPassiveSkillInfo>,
    #[prost(message, optional, tag = "9")]
    pub passive_skill_end_infos: ::core::option::Option<SeqPassiveSkillEndInfo>,
    #[prost(message, optional, tag = "10")]
    pub buff_infos: ::core::option::Option<BuffInfoSync>,
    #[prost(message, optional, tag = "11")]
    pub buff_effect: ::core::option::Option<BuffEffectSync>,
    #[prost(message, repeated, tag = "12")]
    pub fake_bullets: ::prost::alloc::vec::Vec<FakeBulletInfo>,
    #[prost(message, repeated, tag = "13")]
    pub magnetic_ride_queue_change_info_list: ::prost::alloc::vec::Vec<MagneticRideQueueChangeInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AoiSyncToMeDelta {
    #[prost(message, optional, tag = "1")]
    pub base_delta: ::core::option::Option<AoiSyncDelta>,
    #[prost(int64, repeated, tag = "2")]
    pub sync_hate_ids: ::prost::alloc::vec::Vec<i64>,
    #[prost(message, repeated, tag = "3")]
    pub sync_skill_c_ds: ::prost::alloc::vec::Vec<SkillCd>,
    #[prost(message, repeated, tag = "4")]
    pub fight_res_c_ds: ::prost::alloc::vec::Vec<FightResCd>,
    #[prost(int64, tag = "5")]
    pub uuid: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Attr {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub raw_data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttrCollection {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(message, repeated, tag = "2")]
    pub attrs: ::prost::alloc::vec::Vec<Attr>,
    #[prost(message, repeated, tag = "3")]
    pub map_attrs: ::prost::alloc::vec::Vec<MapAttr>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuffEffect {
    #[prost(enumeration = "EBuffEventType", tag = "1")]
    pub r#type: i32,
    #[prost(int32, tag = "2")]
    pub buff_uuid: i32,
    #[prost(int64, tag = "3")]
    pub host_uuid: i64,
    #[prost(int64, tag = "4")]
    pub trigger_time: i64,
    #[prost(message, repeated, tag = "5")]
    pub logic_effect: ::prost::alloc::vec::Vec<BuffEffectLogicInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuffEffectLogicInfo {
    #[prost(enumeration = "EBuffEffectLogicPbType", tag = "1")]
    pub effect_type: i32,
    #[prost(bytes = "vec", tag = "2")]
    pub raw_data: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag = "3")]
    pub is_loop: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuffEffectSync {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(message, repeated, tag = "2")]
    pub buff_effects: ::prost::alloc::vec::Vec<BuffEffect>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BuffInfo {
    #[prost(int32, tag = "1")]
    pub buff_uuid: i32,
    #[prost(int32, tag = "2")]
    pub base_id: i32,
    #[prost(int32, tag = "3")]
    pub level: i32,
    #[prost(int64, tag = "4")]
    pub host_uuid: i64,
    #[prost(int32, tag = "5")]
    pub table_uuid: i32,
    #[prost(int64, tag = "6")]
    pub create_time: i64,
    #[prost(int64, tag = "7")]
    pub fire_uuid: i64,
    #[prost(int32, tag = "8")]
    pub layer: i32,
    #[prost(int32, tag = "9")]
    pub part_id: i32,
    #[prost(int32, tag = "10")]
    pub count: i32,
    #[prost(int32, tag = "11")]
    pub duration: i32,
    #[prost(message, optional, tag = "12")]
    pub fight_source_info: ::core::option::Option<FightSourceInfo>,
    #[prost(message, optional, tag = "13")]
    pub logic_effect: ::core::option::Option<BuffEffectLogicInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BuffInfoSync {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(message, repeated, tag = "2")]
    pub buff_infos: ::prost::alloc::vec::Vec<BuffInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BulletEvent {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(int32, tag = "2")]
    pub enter_stage_id: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ClientHitPartInfo {
    #[prost(int32, tag = "1")]
    pub part_id: i32,
    #[prost(message, optional, tag = "2")]
    pub damage_pos: ::core::option::Option<Vector3>,
    #[prost(int64, tag = "3")]
    pub damage_val: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventData {
    #[prost(int32, tag = "1")]
    pub event_type: i32,
    #[prost(int32, repeated, tag = "2")]
    pub int_params: ::prost::alloc::vec::Vec<i32>,
    #[prost(int64, repeated, tag = "3")]
    pub long_params: ::prost::alloc::vec::Vec<i64>,
    #[prost(float, repeated, tag = "4")]
    pub float_params: ::prost::alloc::vec::Vec<f32>,
    #[prost(string, repeated, tag = "5")]
    pub str_params: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventDataList {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(message, repeated, tag = "2")]
    pub events: ::prost::alloc::vec::Vec<EventData>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct FakeBulletInfo {
    #[prost(int32, tag = "1")]
    pub uuid: i32,
    #[prost(int32, tag = "2")]
    pub bullet_id: i32,
    #[prost(int64, tag = "3")]
    pub target_id: i64,
    #[prost(int32, tag = "4")]
    pub part_id: i32,
    #[prost(message, optional, tag = "5")]
    pub offset: ::core::option::Option<Vector3>,
    #[prost(message, optional, tag = "6")]
    pub rotate: ::core::option::Option<Vector3>,
    #[prost(int32, tag = "7")]
    pub skin_id: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FightResCd {
    #[prost(int32, tag = "1")]
    pub res_id: i32,
    #[prost(int64, tag = "2")]
    pub begin_time: i64,
    #[prost(int32, tag = "3")]
    pub duration: i32,
    #[prost(int32, tag = "4")]
    pub valid_cd_time: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FightSourceInfo {
    #[prost(int32, tag = "1")]
    pub fight_source_type: i32,
    #[prost(int32, tag = "2")]
    pub source_config_id: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MagneticRidePassengerChangeInfo {
    #[prost(message, repeated, tag = "1")]
    pub passenger_change_list: ::prost::alloc::vec::Vec<PassengerChangeParam>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MagneticRidePathPointChangeInfo {
    #[prost(message, repeated, tag = "1")]
    pub path_point_change_list: ::prost::alloc::vec::Vec<PathPointChangeParam>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MagneticRideQueueChangeInfo {
    #[prost(int64, tag = "1")]
    pub queue_uuid: i64,
    #[prost(message, optional, tag = "2")]
    pub passenger_change_info: ::core::option::Option<MagneticRidePassengerChangeInfo>,
    #[prost(message, optional, tag = "3")]
    pub path_point_change_info: ::core::option::Option<MagneticRidePathPointChangeInfo>,
    #[prost(bool, tag = "4")]
    pub is_circle: bool,
    #[prost(bool, tag = "5")]
    pub is_remove: bool,
    #[prost(float, tag = "6")]
    pub path_length: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MapAttr {
    #[prost(bool, tag = "1")]
    pub is_clear: bool,
    #[prost(int32, tag = "2")]
    pub id: i32,
    #[prost(message, repeated, tag = "3")]
    pub attrs: ::prost::alloc::vec::Vec<MapAttrValue>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MapAttrValue {
    #[prost(bool, tag = "1")]
    pub is_remove: bool,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "3")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PassengerChangeParam {
    #[prost(bool, tag = "1")]
    pub is_add_passenger: bool,
    #[prost(int64, tag = "2")]
    pub add_or_remove_uuid: i64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PassiveSkillInfo {
    #[prost(int32, tag = "1")]
    pub uuid: i32,
    #[prost(int64, tag = "2")]
    pub target_uuid: i64,
    #[prost(int64, tag = "3")]
    pub stage_begin_time: i64,
    #[prost(int64, tag = "4")]
    pub begin_time: i64,
    #[prost(int32, tag = "5")]
    pub stage_play_num: i32,
    #[prost(int32, tag = "6")]
    pub skill_id: i32,
    #[prost(int32, tag = "7")]
    pub skill_level: i32,
    #[prost(int32, tag = "8")]
    pub skill_stage: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PathPointChangeParam {
    #[prost(int32, tag = "1")]
    pub operation: i32,
    #[prost(message, optional, tag = "2")]
    pub add_point: ::core::option::Option<Position>,
    #[prost(int32, tag = "3")]
    pub remove_point_count: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Position {
    #[prost(float, tag = "1")]
    pub x: f32,
    #[prost(float, tag = "2")]
    pub y: f32,
    #[prost(float, tag = "3")]
    pub z: f32,
    #[prost(float, tag = "4")]
    pub dir: f32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SeqPassiveSkillEndInfo {
    #[prost(int64, tag = "1")]
    pub actor_uuid: i64,
    #[prost(int64, repeated, tag = "2")]
    pub uuids: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SeqPassiveSkillInfo {
    #[prost(int64, tag = "1")]
    pub actor_uuid: i64,
    #[prost(message, repeated, tag = "2")]
    pub passive_infos: ::prost::alloc::vec::Vec<PassiveSkillInfo>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SkillCd {
    #[prost(int32, tag = "1")]
    pub skill_level_id: i32,
    #[prost(int64, tag = "2")]
    pub begin_time: i64,
    #[prost(int32, tag = "3")]
    pub duration: i32,
    #[prost(enumeration = "ESkillCdType", tag = "4")]
    pub skill_cd_type: i32,
    #[prost(int32, tag = "5")]
    pub valid_cd_time: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SkillEffect {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(message, repeated, tag = "2")]
    pub damages: ::prost::alloc::vec::Vec<SyncDamageInfo>,
    #[prost(int64, tag = "3")]
    pub total_damage: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncDamageInfo {
    #[prost(enumeration = "EDamageSource", tag = "1")]
    pub damage_source: i32,
    #[prost(bool, tag = "2")]
    pub is_miss: bool,
    #[prost(bool, tag = "3")]
    pub is_crit: bool,
    #[prost(enumeration = "EDamageType", tag = "4")]
    pub r#type: i32,
    #[prost(int32, tag = "5")]
    pub type_flag: i32,
    #[prost(int64, tag = "6")]
    pub value: i64,
    #[prost(int64, tag = "7")]
    pub actual_value: i64,
    #[prost(int64, tag = "8")]
    pub lucky_value: i64,
    #[prost(int64, tag = "9")]
    pub hp_lessen_value: i64,
    #[prost(int64, tag = "10")]
    pub shield_lessen_value: i64,
    #[prost(int64, tag = "11")]
    pub attacker_uuid: i64,
    #[prost(int32, tag = "12")]
    pub owner_id: i32,
    #[prost(int32, tag = "13")]
    pub owner_level: i32,
    #[prost(int32, tag = "14")]
    pub owner_stage: i32,
    #[prost(int32, tag = "15")]
    pub hit_event_id: i32,
    #[prost(bool, tag = "16")]
    pub is_normal: bool,
    #[prost(bool, tag = "17")]
    pub is_dead: bool,
    #[prost(enumeration = "EDamageProperty", tag = "18")]
    pub property: i32,
    #[prost(message, optional, tag = "19")]
    pub damage_pos: ::core::option::Option<Vector3>,
    #[prost(message, repeated, tag = "20")]
    pub part_infos: ::prost::alloc::vec::Vec<ClientHitPartInfo>,
    #[prost(int64, tag = "21")]
    pub top_summoner_id: i64,
    #[prost(message, optional, tag = "22")]
    pub damage_weight: ::core::option::Option<Vector2>,
    #[prost(uint32, tag = "23")]
    pub passive_uuid: u32,
    #[prost(bool, tag = "24")]
    pub is_rainbow: bool,
    #[prost(enumeration = "EDamageMode", tag = "25")]
    pub damage_mode: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DisappearEntity {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MagneticQueueAppearInfo {
    #[prost(int64, repeated, tag = "1")]
    pub passenger_uuid_list: ::prost::alloc::vec::Vec<i64>,
    #[prost(bool, tag = "2")]
    pub is_circle: bool,
    #[prost(float, tag = "3")]
    pub path_length: f32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Entity {
    #[prost(int64, tag = "1")]
    pub uuid: i64,
    #[prost(enumeration = "EEntityType", tag = "2")]
    pub ent_type: i32,
    #[prost(message, optional, tag = "3")]
    pub attrs: ::core::option::Option<AttrCollection>,
    #[prost(message, optional, tag = "4")]
    pub temp_attrs: ::core::option::Option<TempAttrCollection>,
    #[prost(message, optional, tag = "5")]
    pub body_part_infos: ::core::option::Option<ActorBodyPartInfos>,
    #[prost(message, optional, tag = "6")]
    pub passive_skill_infos: ::core::option::Option<SeqPassiveSkillInfo>,
    #[prost(message, optional, tag = "7")]
    pub buff_infos: ::core::option::Option<BuffInfoSync>,
    #[prost(message, optional, tag = "8")]
    pub buff_effect: ::core::option::Option<BuffEffectSync>,
    #[prost(enumeration = "EAppearType", tag = "9")]
    pub appear_type: i32,
    #[prost(map = "int32, message", tag = "10")]
    pub magnetic_ride_queue_change_info_dict:
        ::std::collections::HashMap<i32, MagneticQueueAppearInfo>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncNearDeltaInfo {
    #[prost(message, repeated, tag = "1")]
    pub delta_infos: ::prost::alloc::vec::Vec<AoiSyncDelta>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncNearEntities {
    #[prost(message, repeated, tag = "1")]
    pub appear: ::prost::alloc::vec::Vec<Entity>,
    #[prost(message, repeated, tag = "2")]
    pub disappear: ::prost::alloc::vec::Vec<DisappearEntity>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncToMeDeltaInfo {
    #[prost(message, optional, tag = "1")]
    pub delta_info: ::core::option::Option<AoiSyncToMeDelta>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TempAttr {
    #[prost(int32, tag = "1")]
    pub id: i32,
    #[prost(int32, tag = "2")]
    pub value: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TempAttrCollection {
    #[prost(message, repeated, tag = "1")]
    pub attrs: ::prost::alloc::vec::Vec<TempAttr>,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Vector2 {
    #[prost(float, tag = "1")]
    pub x: f32,
    #[prost(float, tag = "2")]
    pub y: f32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Vector3 {
    #[prost(float, tag = "1")]
    pub x: f32,
    #[prost(float, tag = "2")]
    pub y: f32,
    #[prost(float, tag = "3")]
    pub z: f32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CharBaseInfo {
    #[prost(int64, tag = "1")]
    pub char_id: i64,
    #[prost(string, tag = "2")]
    pub account_id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "3")]
    pub show_id: u32,
    #[prost(uint32, tag = "4")]
    pub server_id: u32,
    #[prost(string, tag = "5")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SceneData {
    #[prost(uint32, tag = "1")]
    pub map_id: u32,
    #[prost(uint32, tag = "2")]
    pub channel_id: u32,
    #[prost(message, optional, tag = "3")]
    pub pos: ::core::option::Option<Position>,
    #[prost(int64, tag = "4")]
    pub level_uuid: i64,
    #[prost(message, optional, tag = "5")]
    pub level_pos: ::core::option::Option<Position>,
    #[prost(uint32, tag = "6")]
    pub level_map_id: u32,
    #[prost(uint32, tag = "7")]
    pub level_revive_id: u32,
    #[prost(uint32, tag = "9")]
    pub plane_id: u32,
    #[prost(uint32, tag = "10")]
    pub scene_layer: u32,
    #[prost(bool, tag = "11")]
    pub can_switch_layer: bool,
    #[prost(string, tag = "13")]
    pub scene_guid: ::prost::alloc::string::String,
    #[prost(string, tag = "14")]
    pub dungeon_guid: ::prost::alloc::string::String,
    #[prost(uint32, tag = "15")]
    pub line_id: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Mod {
    #[prost(map = "int64, message", tag = "2")]
    pub mod_infos: ::std::collections::HashMap<i64, ModInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModInfo {
    #[prost(int32, repeated, tag = "1")]
    pub part_ids: ::prost::alloc::vec::Vec<i32>,
    #[prost(message, optional, tag = "2")]
    pub upgrade_records: ::core::option::Option<ModPartUpgradeRecord>,
    #[prost(int32, tag = "3")]
    pub success_rate: i32,
    #[prost(int32, repeated, tag = "4")]
    pub init_link_nums: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModPartUpgradeRecord {
    #[prost(int32, tag = "1")]
    pub part_id: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ModNewAttr {
    #[prost(int32, repeated, tag = "1")]
    pub mod_parts: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Item {
    #[prost(int32, tag = "1")]
    pub config_id: i32,
    #[prost(int64, tag = "2")]
    pub uuid: i64,
    #[prost(int32, tag = "3")]
    pub quality: i32,
    #[prost(message, optional, tag = "13")]
    pub mod_new_attr: ::core::option::Option<ModNewAttr>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Package {
    #[prost(int32, tag = "1")]
    pub r#type: i32,
    #[prost(int32, tag = "2")]
    pub max_capacity: i32,
    #[prost(map = "int64, message", tag = "4")]
    pub items: ::std::collections::HashMap<i64, Item>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ItemPackage {
    #[prost(map = "int32, message", tag = "1")]
    pub packages: ::std::collections::HashMap<i32, Package>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CharSerialize {
    #[prost(int64, tag = "1")]
    pub char_id: i64,
    #[prost(message, optional, tag = "2")]
    pub char_base: ::core::option::Option<CharBaseInfo>,
    #[prost(message, optional, tag = "3")]
    pub scene_data: ::core::option::Option<SceneData>,
    #[prost(message, optional, tag = "7")]
    pub item_package: ::core::option::Option<ItemPackage>,
    #[prost(message, optional, tag = "57")]
    pub r#mod: ::core::option::Option<Mod>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncContainerData {
    #[prost(message, optional, tag = "1")]
    pub v_data: ::core::option::Option<CharSerialize>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum BodyPartState {
    Default = 0,
    Injury = 1,
    Dead = 2,
}
impl BodyPartState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Default => "BodyPartStateDefault",
            Self::Injury => "BodyPartStateInjury",
            Self::Dead => "BodyPartStateDead",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BodyPartStateDefault" => Some(Self::Default),
            "BodyPartStateInjury" => Some(Self::Injury),
            "BodyPartStateDead" => Some(Self::Dead),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EBuffEffectLogicPbType {
    PlayEffect = 0,
    Gravity = 1,
    ParabolaEffect = 2,
    Linking = 3,
    ConfusionEffect = 4,
    ZoomScale = 5,
    BuffProfessionEffect = 7,
    TeleportBelt = 8,
    BuffEffectRainbow = 9,
    BuffEffectAttrHud = 11,
    BuffEffectStop = 12,
    BuffEffectProgress = 13,
    BuffEffectEnergyDisplay = 14,
    BuffEffectStopAll = 15,
    BuffEffectLayerChange = 16,
    Tension = 17,
}
impl EBuffEffectLogicPbType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PlayEffect => "PlayEffect",
            Self::Gravity => "Gravity",
            Self::ParabolaEffect => "ParabolaEffect",
            Self::Linking => "Linking",
            Self::ConfusionEffect => "ConfusionEffect",
            Self::ZoomScale => "ZoomScale",
            Self::BuffProfessionEffect => "BuffProfessionEffect",
            Self::TeleportBelt => "TeleportBelt",
            Self::BuffEffectRainbow => "BuffEffectRainbow",
            Self::BuffEffectAttrHud => "BuffEffectAttrHUD",
            Self::BuffEffectStop => "BuffEffectStop",
            Self::BuffEffectProgress => "BuffEffectProgress",
            Self::BuffEffectEnergyDisplay => "BuffEffectEnergyDisplay",
            Self::BuffEffectStopAll => "BuffEffectStopAll",
            Self::BuffEffectLayerChange => "BuffEffectLayerChange",
            Self::Tension => "Tension",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PlayEffect" => Some(Self::PlayEffect),
            "Gravity" => Some(Self::Gravity),
            "ParabolaEffect" => Some(Self::ParabolaEffect),
            "Linking" => Some(Self::Linking),
            "ConfusionEffect" => Some(Self::ConfusionEffect),
            "ZoomScale" => Some(Self::ZoomScale),
            "BuffProfessionEffect" => Some(Self::BuffProfessionEffect),
            "TeleportBelt" => Some(Self::TeleportBelt),
            "BuffEffectRainbow" => Some(Self::BuffEffectRainbow),
            "BuffEffectAttrHUD" => Some(Self::BuffEffectAttrHud),
            "BuffEffectStop" => Some(Self::BuffEffectStop),
            "BuffEffectProgress" => Some(Self::BuffEffectProgress),
            "BuffEffectEnergyDisplay" => Some(Self::BuffEffectEnergyDisplay),
            "BuffEffectStopAll" => Some(Self::BuffEffectStopAll),
            "BuffEffectLayerChange" => Some(Self::BuffEffectLayerChange),
            "Tension" => Some(Self::Tension),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EBuffEventType {
    BuffEventUnknown = 0,
    BuffEventAddTo = 1,
    BuffEventRemove = 2,
    BuffEventReplace = 3,
    BuffEventTimer = 4,
    BuffEventStackLayer = 5,
    BuffEventRemoveLayer = 6,
    BuffEventOnHitTargetBefore = 7,
    BuffEventOnHitTargetAfter = 8,
    BuffEventOnHittedBefore = 9,
    BuffEventOnHittedAfter = 10,
    BuffEventOnReachMaxLayer = 11,
    BuffEventHostDeath = 12,
    BuffEventOnSkillHitAfter = 13,
    BuffEventTrigTimingAura = 14,
    BuffEventBodyPartDead = 15,
    BuffEventBodyPartHit = 16,
    BuffEventBodyPartStateChange = 17,
    BuffEventOnPartHittedBefore = 18,
    BuffEventOnPartHittedAfter = 19,
    BuffEventGravitational = 20,
    BuffEventFightResChange = 21,
    BuffEventOnKillActor = 23,
    BuffEventAttrWatcher = 24,
    BuffEventOnHittedLhBefore = 25,
    BuffEventOnBeHittedLhBefore = 26,
    BuffEventAddByTarget = 27,
    BuffEventRemoveByTarget = 28,
    BuffEventInCombatState = 29,
    BuffEventOutCombatState = 30,
    BuffEventSkillBegin = 31,
    BuffEventSkillEnd = 32,
    BuffEventSingingEnd = 34,
    BuffEventSummonBuffAdd = 35,
    BuffEventSummonEntity = 36,
    BuffEventGuideEnd = 37,
    BuffEventOnDelayHit = 39,
    BuffEventTeamBuffAdd = 40,
    BuffEventChangeProfession = 41,
    BuffEventDodgeSuccess = 42,
    BuffEventHealBefore = 43,
    BuffEventHealAfter = 44,
    BuffEventProduceHealBefore = 45,
    BuffEventProduceHealAfter = 46,
    BuffEventShieldBroken = 47,
    BuffEventLinkingStart = 48,
    BuffEventLinkingEnd = 49,
    BuffEventLinkingWatcher = 50,
    BuffEventSuperArmorBroken = 51,
    BuffEventAddedByTargetTag = 52,
    BuffEventAddToTargetTag = 53,
    BuffEventOnBeHitLessenHp = 57,
    BuffEventEnterBreaking = 58,
    BuffEventTeleportBelt = 59,
    BuffEventOnBeHitAfterOnly = 63,
    BuffEventOnHitAfterOnly = 64,
    BuffEventOnBeHealAfterOnly = 65,
    BuffEventOnHealAfterOnly = 66,
    BuffEventHealCalcAttrBefore = 67,
    BuffEventProduceHealCalcAttrBefore = 68,
    BuffEventReviveSuccessEnd = 69,
    BuffEventAfterReviveFirstMove = 70,
    BuffEventMonsterIntoAlert = 71,
    BuffEventMonsterOutAlert = 72,
    BuffEventOnAddShieldCalcBefore = 73,
    BuffEventOnAddShieldBefore = 74,
    BuffEventOnAddShieldAfter = 75,
    BuffEventOnBeAddedShieldCalcBefore = 76,
    BuffEventOnBeAddedShieldBefore = 77,
    BuffEventOnBeAddedShieldAfter = 78,
    BuffEventProgressWatcher = 79,
    BuffEventOnLuckyDamage = 80,
    BuffEventSkillCdEnd = 81,
    BuffEventMotionless = 82,
    BuffEventParticipateKill = 83,
    BuffEventProfessionBdTypeChange = 84,
    BuffEventSingingBegin = 85,
    BuffEventGuideBegin = 86,
    BuffEventRandTimer = 87,
    BuffEventIntoFractureState = 88,
    BuffEventTakeOnRide = 89,
    BuffEventTakeOffRide = 90,
    BuffEventStartJump = 91,
    BuffEventPlayAction = 92,
    BuffEventPlayEmote = 93,
    BuffEventCheck = 1001,
    BuffEventCustomize = 1002,
    BuffEventShapeshiftEndEvent = 1003,
    BuffEventAttrRefresh = 1004,
    BuffEventMonitorTeamKillActor = 1005,
    BuffEventSpecialEffects = 10001,
}
impl EBuffEventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::BuffEventUnknown => "BuffEventUnknown",
            Self::BuffEventAddTo => "BuffEventAddTo",
            Self::BuffEventRemove => "BuffEventRemove",
            Self::BuffEventReplace => "BuffEventReplace",
            Self::BuffEventTimer => "BuffEventTimer",
            Self::BuffEventStackLayer => "BuffEventStackLayer",
            Self::BuffEventRemoveLayer => "BuffEventRemoveLayer",
            Self::BuffEventOnHitTargetBefore => "BuffEventOnHitTargetBefore",
            Self::BuffEventOnHitTargetAfter => "BuffEventOnHitTargetAfter",
            Self::BuffEventOnHittedBefore => "BuffEventOnHittedBefore",
            Self::BuffEventOnHittedAfter => "BuffEventOnHittedAfter",
            Self::BuffEventOnReachMaxLayer => "BuffEventOnReachMaxLayer",
            Self::BuffEventHostDeath => "BuffEventHostDeath",
            Self::BuffEventOnSkillHitAfter => "BuffEventOnSkillHitAfter",
            Self::BuffEventTrigTimingAura => "BuffEventTrigTimingAura",
            Self::BuffEventBodyPartDead => "BuffEventBodyPartDead",
            Self::BuffEventBodyPartHit => "BuffEventBodyPartHit",
            Self::BuffEventBodyPartStateChange => "BuffEventBodyPartStateChange",
            Self::BuffEventOnPartHittedBefore => "BuffEventOnPartHittedBefore",
            Self::BuffEventOnPartHittedAfter => "BuffEventOnPartHittedAfter",
            Self::BuffEventGravitational => "BuffEventGravitational",
            Self::BuffEventFightResChange => "BuffEventFightResChange",
            Self::BuffEventOnKillActor => "BuffEventOnKillActor",
            Self::BuffEventAttrWatcher => "BuffEventAttrWatcher",
            Self::BuffEventOnHittedLhBefore => "BuffEventOnHittedLHBefore",
            Self::BuffEventOnBeHittedLhBefore => "BuffEventOnBeHittedLHBefore",
            Self::BuffEventAddByTarget => "BuffEventAddByTarget",
            Self::BuffEventRemoveByTarget => "BuffEventRemoveByTarget",
            Self::BuffEventInCombatState => "BuffEventInCombatState",
            Self::BuffEventOutCombatState => "BuffEventOutCombatState",
            Self::BuffEventSkillBegin => "BuffEventSkillBegin",
            Self::BuffEventSkillEnd => "BuffEventSkillEnd",
            Self::BuffEventSingingEnd => "BuffEventSingingEnd",
            Self::BuffEventSummonBuffAdd => "BuffEventSummonBuffAdd",
            Self::BuffEventSummonEntity => "BuffEventSummonEntity",
            Self::BuffEventGuideEnd => "BuffEventGuideEnd",
            Self::BuffEventOnDelayHit => "BuffEventOnDelayHit",
            Self::BuffEventTeamBuffAdd => "BuffEventTeamBuffAdd",
            Self::BuffEventChangeProfession => "BuffEventChangeProfession",
            Self::BuffEventDodgeSuccess => "BuffEventDodgeSuccess",
            Self::BuffEventHealBefore => "BuffEventHealBefore",
            Self::BuffEventHealAfter => "BuffEventHealAfter",
            Self::BuffEventProduceHealBefore => "BuffEventProduceHealBefore",
            Self::BuffEventProduceHealAfter => "BuffEventProduceHealAfter",
            Self::BuffEventShieldBroken => "BuffEventShieldBroken",
            Self::BuffEventLinkingStart => "BuffEventLinkingStart",
            Self::BuffEventLinkingEnd => "BuffEventLinkingEnd",
            Self::BuffEventLinkingWatcher => "BuffEventLinkingWatcher",
            Self::BuffEventSuperArmorBroken => "BuffEventSuperArmorBroken",
            Self::BuffEventAddedByTargetTag => "BuffEventAddedByTargetTag",
            Self::BuffEventAddToTargetTag => "BuffEventAddToTargetTag",
            Self::BuffEventOnBeHitLessenHp => "BuffEventOnBeHitLessenHp",
            Self::BuffEventEnterBreaking => "BuffEventEnterBreaking",
            Self::BuffEventTeleportBelt => "BuffEventTeleportBelt",
            Self::BuffEventOnBeHitAfterOnly => "BuffEventOnBeHitAfterOnly",
            Self::BuffEventOnHitAfterOnly => "BuffEventOnHitAfterOnly",
            Self::BuffEventOnBeHealAfterOnly => "BuffEventOnBeHealAfterOnly",
            Self::BuffEventOnHealAfterOnly => "BuffEventOnHealAfterOnly",
            Self::BuffEventHealCalcAttrBefore => "BuffEventHealCalcAttrBefore",
            Self::BuffEventProduceHealCalcAttrBefore => "BuffEventProduceHealCalcAttrBefore",
            Self::BuffEventReviveSuccessEnd => "BuffEventReviveSuccessEnd",
            Self::BuffEventAfterReviveFirstMove => "BuffEventAfterReviveFirstMove",
            Self::BuffEventMonsterIntoAlert => "BuffEventMonsterIntoAlert",
            Self::BuffEventMonsterOutAlert => "BuffEventMonsterOutAlert",
            Self::BuffEventOnAddShieldCalcBefore => "BuffEventOnAddShieldCalcBefore",
            Self::BuffEventOnAddShieldBefore => "BuffEventOnAddShieldBefore",
            Self::BuffEventOnAddShieldAfter => "BuffEventOnAddShieldAfter",
            Self::BuffEventOnBeAddedShieldCalcBefore => "BuffEventOnBeAddedShieldCalcBefore",
            Self::BuffEventOnBeAddedShieldBefore => "BuffEventOnBeAddedShieldBefore",
            Self::BuffEventOnBeAddedShieldAfter => "BuffEventOnBeAddedShieldAfter",
            Self::BuffEventProgressWatcher => "BuffEventProgressWatcher",
            Self::BuffEventOnLuckyDamage => "BuffEventOnLuckyDamage",
            Self::BuffEventSkillCdEnd => "BuffEventSkillCDEnd",
            Self::BuffEventMotionless => "BuffEventMotionless",
            Self::BuffEventParticipateKill => "BuffEventParticipateKill",
            Self::BuffEventProfessionBdTypeChange => "BuffEventProfessionBDTypeChange",
            Self::BuffEventSingingBegin => "BuffEventSingingBegin",
            Self::BuffEventGuideBegin => "BuffEventGuideBegin",
            Self::BuffEventRandTimer => "BuffEventRandTimer",
            Self::BuffEventIntoFractureState => "BuffEventIntoFractureState",
            Self::BuffEventTakeOnRide => "BuffEventTakeOnRide",
            Self::BuffEventTakeOffRide => "BuffEventTakeOffRide",
            Self::BuffEventStartJump => "BuffEventStartJump",
            Self::BuffEventPlayAction => "BuffEventPlayAction",
            Self::BuffEventPlayEmote => "BuffEventPlayEmote",
            Self::BuffEventCheck => "BuffEventCheck",
            Self::BuffEventCustomize => "BuffEventCustomize",
            Self::BuffEventShapeshiftEndEvent => "BuffEventShapeshiftEndEvent",
            Self::BuffEventAttrRefresh => "BuffEventAttrRefresh",
            Self::BuffEventMonitorTeamKillActor => "BuffEventMonitorTeamKillActor",
            Self::BuffEventSpecialEffects => "BuffEventSpecialEffects",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "BuffEventUnknown" => Some(Self::BuffEventUnknown),
            "BuffEventAddTo" => Some(Self::BuffEventAddTo),
            "BuffEventRemove" => Some(Self::BuffEventRemove),
            "BuffEventReplace" => Some(Self::BuffEventReplace),
            "BuffEventTimer" => Some(Self::BuffEventTimer),
            "BuffEventStackLayer" => Some(Self::BuffEventStackLayer),
            "BuffEventRemoveLayer" => Some(Self::BuffEventRemoveLayer),
            "BuffEventOnHitTargetBefore" => Some(Self::BuffEventOnHitTargetBefore),
            "BuffEventOnHitTargetAfter" => Some(Self::BuffEventOnHitTargetAfter),
            "BuffEventOnHittedBefore" => Some(Self::BuffEventOnHittedBefore),
            "BuffEventOnHittedAfter" => Some(Self::BuffEventOnHittedAfter),
            "BuffEventOnReachMaxLayer" => Some(Self::BuffEventOnReachMaxLayer),
            "BuffEventHostDeath" => Some(Self::BuffEventHostDeath),
            "BuffEventOnSkillHitAfter" => Some(Self::BuffEventOnSkillHitAfter),
            "BuffEventTrigTimingAura" => Some(Self::BuffEventTrigTimingAura),
            "BuffEventBodyPartDead" => Some(Self::BuffEventBodyPartDead),
            "BuffEventBodyPartHit" => Some(Self::BuffEventBodyPartHit),
            "BuffEventBodyPartStateChange" => Some(Self::BuffEventBodyPartStateChange),
            "BuffEventOnPartHittedBefore" => Some(Self::BuffEventOnPartHittedBefore),
            "BuffEventOnPartHittedAfter" => Some(Self::BuffEventOnPartHittedAfter),
            "BuffEventGravitational" => Some(Self::BuffEventGravitational),
            "BuffEventFightResChange" => Some(Self::BuffEventFightResChange),
            "BuffEventOnKillActor" => Some(Self::BuffEventOnKillActor),
            "BuffEventAttrWatcher" => Some(Self::BuffEventAttrWatcher),
            "BuffEventOnHittedLHBefore" => Some(Self::BuffEventOnHittedLhBefore),
            "BuffEventOnBeHittedLHBefore" => Some(Self::BuffEventOnBeHittedLhBefore),
            "BuffEventAddByTarget" => Some(Self::BuffEventAddByTarget),
            "BuffEventRemoveByTarget" => Some(Self::BuffEventRemoveByTarget),
            "BuffEventInCombatState" => Some(Self::BuffEventInCombatState),
            "BuffEventOutCombatState" => Some(Self::BuffEventOutCombatState),
            "BuffEventSkillBegin" => Some(Self::BuffEventSkillBegin),
            "BuffEventSkillEnd" => Some(Self::BuffEventSkillEnd),
            "BuffEventSingingEnd" => Some(Self::BuffEventSingingEnd),
            "BuffEventSummonBuffAdd" => Some(Self::BuffEventSummonBuffAdd),
            "BuffEventSummonEntity" => Some(Self::BuffEventSummonEntity),
            "BuffEventGuideEnd" => Some(Self::BuffEventGuideEnd),
            "BuffEventOnDelayHit" => Some(Self::BuffEventOnDelayHit),
            "BuffEventTeamBuffAdd" => Some(Self::BuffEventTeamBuffAdd),
            "BuffEventChangeProfession" => Some(Self::BuffEventChangeProfession),
            "BuffEventDodgeSuccess" => Some(Self::BuffEventDodgeSuccess),
            "BuffEventHealBefore" => Some(Self::BuffEventHealBefore),
            "BuffEventHealAfter" => Some(Self::BuffEventHealAfter),
            "BuffEventProduceHealBefore" => Some(Self::BuffEventProduceHealBefore),
            "BuffEventProduceHealAfter" => Some(Self::BuffEventProduceHealAfter),
            "BuffEventShieldBroken" => Some(Self::BuffEventShieldBroken),
            "BuffEventLinkingStart" => Some(Self::BuffEventLinkingStart),
            "BuffEventLinkingEnd" => Some(Self::BuffEventLinkingEnd),
            "BuffEventLinkingWatcher" => Some(Self::BuffEventLinkingWatcher),
            "BuffEventSuperArmorBroken" => Some(Self::BuffEventSuperArmorBroken),
            "BuffEventAddedByTargetTag" => Some(Self::BuffEventAddedByTargetTag),
            "BuffEventAddToTargetTag" => Some(Self::BuffEventAddToTargetTag),
            "BuffEventOnBeHitLessenHp" => Some(Self::BuffEventOnBeHitLessenHp),
            "BuffEventEnterBreaking" => Some(Self::BuffEventEnterBreaking),
            "BuffEventTeleportBelt" => Some(Self::BuffEventTeleportBelt),
            "BuffEventOnBeHitAfterOnly" => Some(Self::BuffEventOnBeHitAfterOnly),
            "BuffEventOnHitAfterOnly" => Some(Self::BuffEventOnHitAfterOnly),
            "BuffEventOnBeHealAfterOnly" => Some(Self::BuffEventOnBeHealAfterOnly),
            "BuffEventOnHealAfterOnly" => Some(Self::BuffEventOnHealAfterOnly),
            "BuffEventHealCalcAttrBefore" => Some(Self::BuffEventHealCalcAttrBefore),
            "BuffEventProduceHealCalcAttrBefore" => Some(Self::BuffEventProduceHealCalcAttrBefore),
            "BuffEventReviveSuccessEnd" => Some(Self::BuffEventReviveSuccessEnd),
            "BuffEventAfterReviveFirstMove" => Some(Self::BuffEventAfterReviveFirstMove),
            "BuffEventMonsterIntoAlert" => Some(Self::BuffEventMonsterIntoAlert),
            "BuffEventMonsterOutAlert" => Some(Self::BuffEventMonsterOutAlert),
            "BuffEventOnAddShieldCalcBefore" => Some(Self::BuffEventOnAddShieldCalcBefore),
            "BuffEventOnAddShieldBefore" => Some(Self::BuffEventOnAddShieldBefore),
            "BuffEventOnAddShieldAfter" => Some(Self::BuffEventOnAddShieldAfter),
            "BuffEventOnBeAddedShieldCalcBefore" => Some(Self::BuffEventOnBeAddedShieldCalcBefore),
            "BuffEventOnBeAddedShieldBefore" => Some(Self::BuffEventOnBeAddedShieldBefore),
            "BuffEventOnBeAddedShieldAfter" => Some(Self::BuffEventOnBeAddedShieldAfter),
            "BuffEventProgressWatcher" => Some(Self::BuffEventProgressWatcher),
            "BuffEventOnLuckyDamage" => Some(Self::BuffEventOnLuckyDamage),
            "BuffEventSkillCDEnd" => Some(Self::BuffEventSkillCdEnd),
            "BuffEventMotionless" => Some(Self::BuffEventMotionless),
            "BuffEventParticipateKill" => Some(Self::BuffEventParticipateKill),
            "BuffEventProfessionBDTypeChange" => Some(Self::BuffEventProfessionBdTypeChange),
            "BuffEventSingingBegin" => Some(Self::BuffEventSingingBegin),
            "BuffEventGuideBegin" => Some(Self::BuffEventGuideBegin),
            "BuffEventRandTimer" => Some(Self::BuffEventRandTimer),
            "BuffEventIntoFractureState" => Some(Self::BuffEventIntoFractureState),
            "BuffEventTakeOnRide" => Some(Self::BuffEventTakeOnRide),
            "BuffEventTakeOffRide" => Some(Self::BuffEventTakeOffRide),
            "BuffEventStartJump" => Some(Self::BuffEventStartJump),
            "BuffEventPlayAction" => Some(Self::BuffEventPlayAction),
            "BuffEventPlayEmote" => Some(Self::BuffEventPlayEmote),
            "BuffEventCheck" => Some(Self::BuffEventCheck),
            "BuffEventCustomize" => Some(Self::BuffEventCustomize),
            "BuffEventShapeshiftEndEvent" => Some(Self::BuffEventShapeshiftEndEvent),
            "BuffEventAttrRefresh" => Some(Self::BuffEventAttrRefresh),
            "BuffEventMonitorTeamKillActor" => Some(Self::BuffEventMonitorTeamKillActor),
            "BuffEventSpecialEffects" => Some(Self::BuffEventSpecialEffects),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EDamageMode {
    DamageNormal = 0,
    DamagePhysical = 1,
    DamageMagical = 2,
}
impl EDamageMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::DamageNormal => "DamageNormal",
            Self::DamagePhysical => "DamagePhysical",
            Self::DamageMagical => "DamageMagical",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "DamageNormal" => Some(Self::DamageNormal),
            "DamagePhysical" => Some(Self::DamagePhysical),
            "DamageMagical" => Some(Self::DamageMagical),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EDamageProperty {
    General = 0,
    Fire = 1,
    Water = 2,
    Electricity = 3,
    Wood = 4,
    Wind = 5,
    Rock = 6,
    Light = 7,
    Dark = 8,
    Count = 9,
}
impl EDamageProperty {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::General => "General",
            Self::Fire => "Fire",
            Self::Water => "Water",
            Self::Electricity => "Electricity",
            Self::Wood => "Wood",
            Self::Wind => "Wind",
            Self::Rock => "Rock",
            Self::Light => "Light",
            Self::Dark => "Dark",
            Self::Count => "Count",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "General" => Some(Self::General),
            "Fire" => Some(Self::Fire),
            "Water" => Some(Self::Water),
            "Electricity" => Some(Self::Electricity),
            "Wood" => Some(Self::Wood),
            "Wind" => Some(Self::Wind),
            "Rock" => Some(Self::Rock),
            "Light" => Some(Self::Light),
            "Dark" => Some(Self::Dark),
            "Count" => Some(Self::Count),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EDamageSource {
    Skill = 0,
    Bullet = 1,
    Buff = 2,
    Fall = 3,
    FakeBullet = 4,
    Other = 100,
}
impl EDamageSource {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Skill => "EDamageSourceSkill",
            Self::Bullet => "EDamageSourceBullet",
            Self::Buff => "EDamageSourceBuff",
            Self::Fall => "EDamageSourceFall",
            Self::FakeBullet => "EDamageSourceFakeBullet",
            Self::Other => "EDamageSourceOther",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EDamageSourceSkill" => Some(Self::Skill),
            "EDamageSourceBullet" => Some(Self::Bullet),
            "EDamageSourceBuff" => Some(Self::Buff),
            "EDamageSourceFall" => Some(Self::Fall),
            "EDamageSourceFakeBullet" => Some(Self::FakeBullet),
            "EDamageSourceOther" => Some(Self::Other),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EDamageType {
    Normal = 0,
    Miss = 1,
    Heal = 2,
    Immune = 3,
    Fall = 4,
    Absorbed = 5,
}
impl EDamageType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Normal => "Normal",
            Self::Miss => "Miss",
            Self::Heal => "Heal",
            Self::Immune => "Immune",
            Self::Fall => "Fall",
            Self::Absorbed => "Absorbed",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "Normal" => Some(Self::Normal),
            "Miss" => Some(Self::Miss),
            "Heal" => Some(Self::Heal),
            "Immune" => Some(Self::Immune),
            "Fall" => Some(Self::Fall),
            "Absorbed" => Some(Self::Absorbed),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ESkillCdType {
    ESkillCdNormal = 0,
    ESkillCdCharge = 1,
}
impl ESkillCdType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ESkillCdNormal => "ESkillCDNormal",
            Self::ESkillCdCharge => "ESkillCDCharge",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ESkillCDNormal" => Some(Self::ESkillCdNormal),
            "ESkillCDCharge" => Some(Self::ESkillCdCharge),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EAppearType {
    PAppearNone = 0,
    PAppearInRange = 1,
    PAppearTransferIn = 2,
    PAppearFlyLineIn = 3,
    PAppearNpcCreate = 5,
}
impl EAppearType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::PAppearNone => "PAppearNone",
            Self::PAppearInRange => "PAppearInRange",
            Self::PAppearTransferIn => "PAppearTransferIn",
            Self::PAppearFlyLineIn => "PAppearFlyLineIn",
            Self::PAppearNpcCreate => "PAppearNpcCreate",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PAppearNone" => Some(Self::PAppearNone),
            "PAppearInRange" => Some(Self::PAppearInRange),
            "PAppearTransferIn" => Some(Self::PAppearTransferIn),
            "PAppearFlyLineIn" => Some(Self::PAppearFlyLineIn),
            "PAppearNpcCreate" => Some(Self::PAppearNpcCreate),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EEntityType {
    EntErrType = 0,
    EntMonster = 1,
    EntNpc = 2,
    EntSceneObject = 3,
    EntZone = 5,
    EntBullet = 6,
    EntClientBullet = 7,
    EntPet = 8,
    EntChar = 10,
    EntDummy = 11,
    EntDrop = 12,
    EntField = 14,
    EntTrap = 15,
    EntCollection = 16,
    EntStaticObject = 18,
    EntVehicle = 19,
    EntToy = 20,
    EntCommunityHouse = 21,
    EntHouseItem = 22,
    EntCount = 23,
}
impl EEntityType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::EntErrType => "EntErrType",
            Self::EntMonster => "EntMonster",
            Self::EntNpc => "EntNpc",
            Self::EntSceneObject => "EntSceneObject",
            Self::EntZone => "EntZone",
            Self::EntBullet => "EntBullet",
            Self::EntClientBullet => "EntClientBullet",
            Self::EntPet => "EntPet",
            Self::EntChar => "EntChar",
            Self::EntDummy => "EntDummy",
            Self::EntDrop => "EntDrop",
            Self::EntField => "EntField",
            Self::EntTrap => "EntTrap",
            Self::EntCollection => "EntCollection",
            Self::EntStaticObject => "EntStaticObject",
            Self::EntVehicle => "EntVehicle",
            Self::EntToy => "EntToy",
            Self::EntCommunityHouse => "EntCommunityHouse",
            Self::EntHouseItem => "EntHouseItem",
            Self::EntCount => "EntCount",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EntErrType" => Some(Self::EntErrType),
            "EntMonster" => Some(Self::EntMonster),
            "EntNpc" => Some(Self::EntNpc),
            "EntSceneObject" => Some(Self::EntSceneObject),
            "EntZone" => Some(Self::EntZone),
            "EntBullet" => Some(Self::EntBullet),
            "EntClientBullet" => Some(Self::EntClientBullet),
            "EntPet" => Some(Self::EntPet),
            "EntChar" => Some(Self::EntChar),
            "EntDummy" => Some(Self::EntDummy),
            "EntDrop" => Some(Self::EntDrop),
            "EntField" => Some(Self::EntField),
            "EntTrap" => Some(Self::EntTrap),
            "EntCollection" => Some(Self::EntCollection),
            "EntStaticObject" => Some(Self::EntStaticObject),
            "EntVehicle" => Some(Self::EntVehicle),
            "EntToy" => Some(Self::EntToy),
            "EntCommunityHouse" => Some(Self::EntCommunityHouse),
            "EntHouseItem" => Some(Self::EntHouseItem),
            "EntCount" => Some(Self::EntCount),
            _ => None,
        }
    }
}
