<script lang="ts">
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';
	import { Button } from '$lib/components/ui/button';
	import * as Card from '$lib/components/ui/card/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Label } from '$lib/components/ui/label';
	import { Switch } from '$lib/components/ui/switch';
	import { signInAPI, signOut } from '$lib/oauth';
	import { pb } from '$lib/pocketbase';
	import type { UserRecordModel } from '$lib/types/auth';
	import { onMount } from 'svelte';

	let currentUser = $state<UserRecordModel | null>(null);
	let apiKey = $state<string>('');
	let isEnabled = $state<boolean>(false);
	let isGenerating = $state<boolean>(false);
	let isDeleting = $state<boolean>(false);
	let error = $state<string>('');

	// Check if user is authenticated on mount
	onMount(async () => {
		if (pb.authStore.isValid) {
			currentUser = pb.authStore.record as UserRecordModel;
			// Load existing API key
			try {
				const records = await pb.collection('api_keys').getList(1, 1);
				if (records.items.length > 0) {
					apiKey = records.items[0].api_key;
				}
				isEnabled = !!apiKey;
			} catch (err) {
				console.error('Failed to load API key:', err);
			}
		}
	});

	async function generateKey() {
		if (!currentUser || isGenerating) return;

		isGenerating = true;
		error = '';

		try {
			// Delete existing API key record for the user
			const records = await pb.collection('api_keys').getList(1, 1);
			if (records.items.length > 0) {
				await pb.collection('api_keys').delete(records.items[0].id);
			}
			// Create new record (api_key will be autogenerated)
			const result = await pb.collection('api_keys').create({ user: currentUser.id });
			apiKey = result.api_key;
			isEnabled = true;
		} catch (err: unknown) {
			error = err instanceof Error ? err.message : 'Failed to generate API key';
			isEnabled = false; // Reset since generation failed
		} finally {
			isGenerating = false;
		}
	}

	async function deleteKey() {
		if (!currentUser || isDeleting) return;

		isDeleting = true;
		error = '';

		try {
			// Delete existing API key record for the user
			const records = await pb.collection('api_keys').getList(1, 1);
			if (records.items.length > 0) {
				await pb.collection('api_keys').delete(records.items[0].id);
			}
			apiKey = '';
			isEnabled = false;
		} catch (err: unknown) {
			error = err instanceof Error ? err.message : 'Failed to delete API key';
			isEnabled = true; // Reset since deletion failed
		} finally {
			isDeleting = false;
		}
	}

	async function handleToggle(checked: boolean) {
		if (checked) {
			// Enable API support - generate key
			await generateKey();
		} else {
			// Disable API support - delete key
			await deleteKey();
		}
	}

	async function handleSignIn(): Promise<void> {
		try {
			await signInAPI();
			// After sign in, set user
			currentUser = pb.authStore.record as UserRecordModel;
		} catch (err: unknown) {
			error = err instanceof Error ? err.message : 'Sign in failed';
		}
	}

	function redirectToDesktopApp() {
		if (!apiKey) return;
		const deepLink = `myapp://auth?key=${encodeURIComponent(apiKey)}`;
		window.location.href = deepLink;
	}

	function copyKeyToClipboard() {
		if (!apiKey) return;
		navigator.clipboard.writeText(apiKey);
	}

	function signOutAndRedirect() {
		signOut();
		goto(resolve('/'));
	}
</script>

<div class="flex h-screen w-full items-center justify-center px-4">
	<Card.Root class="mx-auto w-full max-w-2xl">
		<Card.Header>
			<Card.Title class="text-2xl">API Key Management</Card.Title>
		</Card.Header>
		<Card.Content>
			{#if !currentUser}
				<div class="space-y-6 text-center">
					<p class="text-muted-foreground text-lg">
						You need to sign in to generate an API key for your DPS meter app.
					</p>
					<div class="space-y-4">
						<Button onclick={handleSignIn} class="mx-auto w-full max-w-sm"
							>Sign in with Discord</Button
						>
						{#if error}
							<p class="text-destructive text-sm">{error}</p>
							<button
								class="text-sm text-blue-600 hover:underline"
								onclick={() => goto(resolve('/'))}
							>
								← Back home
							</button>
						{/if}
					</div>
				</div>
			{:else}
				<div class="space-y-6">
					<p class="text-muted-foreground mb-4">Control API access for your applications.</p>

					<div class="mb-4 flex items-center space-x-2">
						<Switch
							id="api-support"
							checked={isEnabled}
							onCheckedChange={handleToggle}
							disabled={isGenerating || isDeleting}
						/>
						<Label for="api-support">Enable API Support</Label>
					</div>

					{#if apiKey}
						<div class="space-y-4">
							<div>
								<p class="mb-2 block text-sm font-medium">Your API Key:</p>
								<Input
									type="password"
									value={apiKey}
									readonly
									class="cursor-text font-mono text-sm break-all select-all"
									placeholder="••••••••••••••••••••••••••••••••••••••••••••••••••"
									onfocus={(e: FocusEvent) => {
										const input = e.target as HTMLInputElement;
										input.type = 'text';
										input.select();
									}}
									onblur={(e: FocusEvent) => {
										const input = e.target as HTMLInputElement;
										input.type = 'password';
									}}
									onclick={(e: MouseEvent) => {
										const input = e.target as HTMLInputElement;
										input.type = 'text';
										input.select();
									}}
								/>
							</div>

							<div class="flex flex-col gap-3 sm:flex-row">
								<Button onclick={redirectToDesktopApp} class="flex-1">Open Desktop App</Button>
								<Button onclick={copyKeyToClipboard} variant="outline" class="flex-1">
									Copy API Key
								</Button>
							</div>

							<div
								class="rounded-md border border-blue-200 bg-blue-50 p-4 dark:border-blue-800 dark:bg-blue-950"
							>
								<h3 class="mb-2 font-semibold text-blue-900 dark:text-blue-100">Instructions:</h3>
								<ol
									class="list-inside list-decimal space-y-1 text-sm text-blue-800 dark:text-blue-200"
								>
									<li>Copy this API key or click "Open Desktop App"</li>
									<li>For manual copy, paste the API key in your DPS meter app when prompted</li>
									<li>This API key grants access to your account - keep it secure!</li>
								</ol>
							</div>

							<div class="flex items-center justify-between border-t pt-4">
								<button
									class="text-muted-foreground hover:text-foreground text-sm"
									onclick={() => goto(resolve('/'))}
								>
									← Back to home
								</button>
								<Button onclick={signOutAndRedirect} variant="ghost" size="sm">Sign out</Button>
							</div>
						</div>
					{/if}

					{#if error}
						<p class="text-destructive mt-4 text-sm">{error}</p>
					{/if}
				</div>
			{/if}
		</Card.Content>
	</Card.Root>
</div>
